---
# tasks file for vault

- name: Variables by OS
  include_vars: "{{ item }}"
  tags: always
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- import_tasks: vault_pre_install.yml
  tags:
    - vault-pre-install

- import_tasks: vault_install.yml
  tags:
    - vault-install

- import_tasks: vault_post_install.yml
  tags:
    - vault-post-install

- include_tasks: vault_post_install_policy.yml
  with_items: "{{ vault_policies }}"
  run_once: true
  tags:
    - vault-post-install

- include_tasks: vault_post_install_role_token.yml
  with_items: "{{ vault_role_tokens }}"
  run_once: true
  tags:
    - vault-post-install
