---

- name: Kernel capabilities
  when:
    - install_vault | lower == 'true'
  command: setcap cap_ipc_lock=+ep /usr/local/bin/vault

- name: Sysconfig
  template: src=vault.sysconfig.j2 dest={{ vault_sysconfig }}
  notify: restart vault

- name: Vault main configuration file
  template: src=vault.hcl.j2 dest=/etc/vault.d/vault.hcl
  notify: restart vault

#- name: Telegraf configuration
#  template: src=vault.telegraf.conf.j2 dest=/etc/telegraf/telegraf.d/vault.conf
#  notify: restart telegraf
#  when: vault_config_telegraf == true

#- name: Auto-complétion
#  become: no
#  command: vault -autocomplete-install
#  register: vault_autocomplete

- name: Consul monitoring
  when:
    - configure_consul_vault_ui | lower == 'true'
  with_items: "{{ vault_vault_ui }}"
  notify: reload consul
  template:
      src: service.consul.json.j2
      dest: "{{ vault_consul_services_path }}/{{ item.service.name }}.json"

# TODO: [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
# TODO: [INFO]  core: seal configuration missing, not initialized
# TODO: https://shapeshed.com/hashicorp-vault-ldap/

- name: Flush handlers before post configuration
  meta: flush_handlers

- name: Ensure vault is running
  service: name=vault state=started

- name: Vault post configuration
  run_once: true
  block:
    - name: Init vault
      register: vault_init_result
      environment:
        VAULT_ADDR: "{{ vault_addr }}"
        CONSUL_HTTP_TOKEN: "{{ vault_consul_token }}"
      shell: >
          consul lock vault_init \
              vault operator init \
                  -key-shares=3 \
                  -key-threshold=2 \
                  -format=json

    - name: Continue if vault is not initialized
      when: vault_init_result.stderr_lines | length == 0
      block:
        - name: Set init facts
          set_fact: vault_init="{{ vault_init_result.stdout | from_json }}"

        - name: Unseal vault
          shell: consul lock vault_init vault operator unseal {{ item }}
          with_items: "{{ vault_init.unseal_keys_hex }}"
          environment:
            VAULT_ADDR: "{{ vault_addr }}"
            CONSUL_HTTP_TOKEN: "{{ vault_consul_token }}"
        
        - name: Set root token
          set_fact: vault_root_token="{{ vault_init.root_token }}"
            
    - name: Get already created token
      when: vault_init_result.stderr_lines | length > 0
      block:
        - name: Check file
          stat: path="{{ vault_env_root_path }}/.vault.env"
          register: vault_env_result

        - name: Get root token from file
          when: vault_env_result.stat.exists is true
          set_fact:
              vault_root_token: "{{ lookup('file', '{{ vault_env_root_path }}/.vault.env') | regex_replace('^VAULT_TOKEN=','')}}"

        - name: Get root token from consul kv
          until: consul_kv_root_token.stdout | length > 0
          retries: 10
          delay: 30
          when:
            - vault_env_result.stat.exists is false
            - vault_token_store_consul_kv | lower == 'true'
          register: consul_kv_root_token
          shell: consul kv get vault/root_token
          environment:
            CONSUL_HTTP_TOKEN: "{{ vault_consul_token }}"

        - name: Set local fact
          set_fact:
            vault_root_token: "{{ consul_kv_root_token.stdout }}"

    - name: Get vault status
      when: vault_root_token is defined
      shell: vault status
      register: vault_status
      environment:
        VAULT_TOKEN: "{{ vault_root_token }}"
        VAULT_ADDR: "{{ vault_addr }}"

    - name: Configure vault
      when:
        - vault_root_token is defined
        - vault_status.stderr_lines | length == 0
        - vault_status.stdout_lines[12] | regex_search(' active$') != None
      block:
        - name: Auth engines configuration
          import_tasks: vault_post_install_auth_engines.yml

        - name: Secrets engines configuration
          import_tasks: vault_post_install_secrets_engines.yml

        # TODO: set a local fact in pre_install to manage this
        - name: Create an env file containing the token
          when:
            - vault_token_create_env_file | lower == 'true'
          block:
            - name: Create .vault.env
              file:
                path: "{{ vault_env_root_path }}/.vault.env"
                state: touch

            - name: Create an env file containing the token
              lineinfile:
                path: "{{ vault_env_root_path }}/.vault.env"
                state: present
                regexp: "^(VAULT_TOKEN=.+){0,1}$"
                line: "VAULT_TOKEN={{ vault_root_token }}"

            - name: Store the bootstrap token into consul
              when: vault_token_store_consul_kv | lower == 'true'
              command: consul kv put vault/root_token {{ vault_root_token }}
