---
 
- name: Configure database secret engine
  when: vault_secrets_engine_databases | length > 0
  block:
    - name: Create script
      template:
         src: vault_database_engine.sh.j2
         dest: /dev/shm/vault_database_engine.sh

    - name: Run script
      environment:
         VAULT_TOKEN: "{{ vault_root_token }}"
         VAULT_ADDR: "{{ vault_addr }}"
         CONSUL_HTTP_TOKEN: "{{ vault_consul_token }}"     
      shell: >
         sh /dev/shm/vault_database_engine.sh

    - name: Cleanup script
      file: path=/dev/shm/vault_database_engine.sh state=absent

- name: Configure consul secret engine
  when: vault_secrets_engine_consul | length > 0
  block:
    - name: Create the consul secrets engine
      with_items: "{{ vault_secrets_engine_consul }}"
      environment:
         VAULT_TOKEN: "{{ vault_root_token }}"
         VAULT_ADDR: "{{ vault_addr }}"
      shell: >
         vault secrets enable \
             -path={{ item.name }} \
             {% if item.description is defined %}
             -description="{{ item.description }}" \
             {% endif %}
             consul

    - name: Set the access token
      with_items: "{{ vault_secrets_engine_consul }}"
      environment:
         VAULT_TOKEN: "{{ vault_root_token }}"
         VAULT_ADDR: "{{ vault_addr }}"
      shell: >
         vault write {{ item.name }}/config/access \
             address={{ item.address }} \
             token={{ item.token }}
