---
 
- name: Post-Install | secrets engines | Configure database secret engine
  when:
    - vault_secrets_engine_databases is defined
    - vault_secrets_engine_databases | length > 0
  block:
    - name: Post-Install | secrets engines | Database secrets engine - Create script
      template:
         src: vault_database_engine.sh.j2
         dest: /dev/shm/vault_database_engine.sh

    - name: Post-Install | secrets engines | Database secrets engine - Run script
      environment:
         VAULT_TOKEN: "{{ vault_root_token }}"
         VAULT_ADDR: "{{ vault_addr }}"
      shell: >
         sh /dev/shm/vault_database_engine.sh

    - name: Post-Install | secrets engines | Database secrets engine - Cleanup script
      file: path=/dev/shm/vault_database_engine.sh state=absent

- name: Post-Install | secrets engines | Configure consul secret engine
  when: vault_secrets_engine_consul | length > 0
  block:
    - name: Post-Install | secrets engines | Consul - Create the secrets engine
      with_items: "{{ vault_secrets_engine_consul }}"
      environment:
         VAULT_TOKEN: "{{ vault_root_token }}"
         VAULT_ADDR: "{{ vault_addr }}"
      shell: >
         vault secrets enable \
             -path={{ item.name }} \
             {% if item.description is defined %}
             -description="{{ item.description }}" \
             {% endif %}
             consul

    - name: Post-Install | secrets engines | Consul - Set the access token
      with_items: "{{ vault_secrets_engine_consul }}"
      environment:
         VAULT_TOKEN: "{{ vault_root_token }}"
         VAULT_ADDR: "{{ vault_addr }}"
      shell: >
         vault write {{ item.name }}/config/access \
             address={{ item.address }} \
             token={{ item.token }}
