---

- name: restart vault
  service: name=vault state=restarted enabled=yes

- name: reload systemd
  command: systemctl daemon-reload

- name: reload firewalld
  command: firewall-cmd --reload

- name: reload consul
  command: "{{ consul_bin }} reload"
